name: "PR Checks"
on: [pull_request]

jobs:
  build:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.7.7'
            channel: 'stable'
            cache: true

      - name: Run Danger
        run: |
          cd $HOME
          cd $GITHUB_WORKSPACE
          cd games_services
          flutter pub get
          cd ..
          cd games_services_platform_interface
          flutter pub get
          cd ..
          npm install --global yarn
          yarn add danger --dev
          yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}